if not FlightTracker then return end

FlightTracker.PreloadedNodes = {
    ["Kalimdor"] = {
        Alliance = {
            "Astranaar, Ashenvale",
            "Auberdine, Darkshore",
            "Bael Hardul, Stonetalon Mountains",
            "Cenarion Hold, Silithus",
            "Everlook, Winterspring",
            "Feathermoon, Feralas",
            "Gadgetzan, Tanaris",
            "Marshal's Refuge, Un'Goro Crater",
            "Moonglade",
            "Narvalis Point, Moonwhisper Coast",
            "Nijel's Point, Desolace",
            "Nordanaar, Hyjal",
            "Ratchet, The Barrens",
            "Rut'theran Village, Teldrassil",
            "Shimmerstar Lake, Moonwhisper Coast",
            "Stonetalon Peak, Stonetalon Mountains",
            "Talrendis Point, Azshara",
            "Talonbranch Glade, Felwood",
            "Tel Co. Basecamp, Tel'Abim",
            "Thalanaar, Feralas",
            "Theramore, Dustwallow Marsh",
        },
        Horde = {
            "Bloodvenom Post, Felwood",
            "Brackenwall Village, Dustwallow Marsh",
            "Camp Mojache, Feralas",
            "Camp Taurajo, The Barrens",
            "Cenarion Hold, Silithus",
            "Crossroads, The Barrens",
            "Everlook, Winterspring",
            "Freewind Post, Thousand Needles",
            "Gadgetzan, Tanaris",
            "Marshal's Refuge, Un'Goro Crater",
            "Moonglade",
            "Moonhoof Village, Moonwhisper Coast",
            "Mudsprocket, Dustwallow Marsh",
            "Nordanaar, Hyjal",
            "Orgrimmar, Durotar",
            "Ratchet, The Barrens",
            "Shadowprey Village, Desolace",
            "Shimmerstar Lake, Moonwhisper Coast",
            "Slickwick Oil Rig, Tanaris",
            "Splintertree Post, Ashenvale",
            "Sun Rock Retreat, Stonetalon Mountains",
            "Tel Co. Basecamp, Tel'Abim",
            "Thunder Bluff, Mulgore",
            "Valormok, Azshara",
            "Zoram'gar Outpost, Ashenvale",
        },
    },
    ["Eastern Kingdoms"] = {
        Alliance = {
            "Aerie Peak, The Hinterlands",
            "Alah'Thalas, Thalassian Highlands",
            "Ambershire, Northwind",
            "Booty Bay, Stranglethorn",
            "Caelan's Rest, Lapidis Isle",
            "Chillwind Camp, Western Plaguelands",
            "Darkshire, Duskwood",
            "Dun Agrath, Wetlands",
            "Dun Kithas, Grim Reaches",
            "Gnomeregan Reclamation Facility, Dun Morogh",
            "Ironforge Airfields, Dun Morogh",
            "Ironforge, Dun Morogh",
            "Lakeshire, Redridge",
            "Light's Hope Chapel, Eastern Plaguelands",
            "Menethil Harbor, Wetlands",
            "Morgan's Vigil, Burning Steppes",
            "Nethergarde Keep, Blasted Lands",
            "Ravenshire, Gilneas",
            "Refuge Pointe, Arathi",
            "SI:7 Outpost, Balor",
            "Sentinel Hill, Westfall",
            "Southshore, Hillsbrad",
            "Stormwind, Elwynn Forest",
            "Thelsamar, Loch Modan",
            "Thorium Point, Searing Gorge",
        },
        Horde = {
            "Booty Bay, Stranglethorn",
            "Flame Crest, Burning Steppes",
            "Grom'gol, Stranglethorn",
            "Hammerfall, Arathi",
            "Kargath, Badlands",
            "Light's Hope Chapel, Eastern Plaguelands",
            "Maul'Ogg Refuge, Gillijim's Isle",
            "Revantusk Village, The Hinterlands",
            "Shatterblade Post, Grim Reaches",
            "Steepcliff Port, Tirisfal",
            "Stillward Church, Gilneas",
            "Stonard, Swamp of Sorrows",
            "Stormbreaker Point, Balor",
            "Tarren Mill, Hillsbrad",
            "The Sepulcher, Silverpine Forest",
            "Thorium Point, Searing Gorge",
            "Undercity, Tirisfal",
        },
    },
}
